[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''if (self == G.hand or self == G.deck or self == G.discard or self == G.play) and G.view_deck and G.view_deck[1] and G.view_deck[1].cards then return end'''
position = "after"
payload = '''self.cards = self.cards or {}'''
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''if self.children.view_deck then'''
position = "before"
payload = '''if not self.children or not self.children.view_deck then return end'''
match_indent = true